name: Build and Export Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x' # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore
      working-directory: /ShuffleMOTD

    - name: Build
      run: dotnet build --configuration Release
      working-directory: /ShuffleMOTD

    - name: Publish
      run: dotnet publish --configuration Release
      working-directory: /ShuffleMOTD

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ShuffleMOTD
        path: /ShuffleMOTD/bin/Release/ShuffleMOTD.obby